### ISSUE TITLE
Quick buy - starting items 

### ISSUE THREAD

**Issue by Korczak** [yasp-dota/rapier#5]
Hello, is there a possibility to get information about starting items which are quick buy. There is no information about these items. To sum up, i can retrieve information about purchased items, however starting items are inaccessible.

**Comment by howardchung** [comment]
This library doesn't offer entity parsing which is one way to get that data (you can have it dump a snapshot of a player's owned items at any point.  If you need that I suggest using either clarity or manta replay parsing libraries.

**Comment by Korczak** [comment]
Okay, thanks a lot.
